version: "3.9"
services:
  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
